### ISSUE TITLE
OPLS Implementation?

### ISSUE THREAD

**Issue by Parker-Fl** [fhh2626/BFEE2#87]
Hi,
In your Nature Protocols procedure, OPLS was listed as an available FF. However, I only see options for CHARMM and AMBER when running BFEE2GUI. Can top_ and par_ files from the OPLS-AA site be added in the Force Field section? CHARMM does not support the molecule that I am parameterizing.

**Comment by fhh2626** [comment]
Hi @Parker-Fl ,

"CHARMM" and "Amber" indicate the formats of input files. For instance, you can always generate CHARMM-formatted input files for the OPLS-FF using CHARMM-GUI. 

However, since OPLS uses special combination rules. You need to add "vdwGeometricSigma  on" manually in all the config files. I am thinking if this can be automated in the next version of BFEE2.

Good luck,
Haohao

**Comment by fhh2626** [comment]
Addressed by d96655d. You can turn to the dev branch or wait for the next release.
